name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  nebula_dart_gdbc:
    path: ..

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
