name: nebula_dart_gdbc
description: A database driver for nebula graph based on dart_gdbc
version: 0.0.1
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  # nebula_graph:
  #   path: D:/work/dudu-ltd/nebula_dart/nebula_graph
  fbthrift: ^1.0.0+1
  dart_gdbc: ^0.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
